"""Per-AM daily briefing generator.

Architecture is a small LangGraph: rank actions → optionally enrich with LLM
narrative → render markdown → persist Briefing row. The graph is overkill for
v0 (it's basically linear) but using LangGraph here keeps the door open for
future steps like account-context fetch, peer comparison, web research, etc.
"""

from __future__ import annotations

import json
import os
import uuid
from dataclasses import asdict
from datetime import datetime, timezone
from typing import Annotated, Any, TypedDict

import structlog
from langgraph.graph import END, START, StateGraph
from operator import add

from aam.db import Briefing, session
from aam.ranker import RankedAction, rank_for_am
from aam.scoring import latest_signals_per_account
from aam.slack import send_briefing_dm
from aam.teams_channel import post_briefing as post_teams_briefing
from aam.teams_dm import send_proactive_dm as send_teams_dm
from aam.tracing import traced

log = structlog.get_logger()
MODEL = os.environ.get("AAM_MODEL", "claude-sonnet-4-6")


class _BriefingState(TypedDict, total=False):
    am_email: str
    actions: list[dict]   # serialized RankedAction
    narrative: str
    markdown: str
    events: Annotated[list[dict], add]


# ---------- Nodes ----------

@traced(name="rank_actions")
async def _node_rank(state: _BriefingState) -> dict[str, Any]:
    pairs = await latest_signals_per_account()
    actions = rank_for_am(state["am_email"], pairs, top_n=5)
    serialized = [
        {
            **asdict(a),
            "account": {
                "id": a.account.id,
                "name": a.account.name,
                "tier": a.account.tier,
                "arr": a.account.arr,
                "industry": a.account.industry,
                "domain": a.account.domain,
            },
        }
        for a in actions
    ]
    return {"actions": serialized, "events": [{"kind": "ranked", "count": len(serialized)}]}


@traced(name="generate_narrative", as_type="generation")
async def _node_narrative(state: _BriefingState) -> dict[str, Any]:
    if not state["actions"]:
        return {"narrative": "_No priority actions today. All accounts steady._"}
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return {"narrative": _stub_narrative(state["actions"])}

    from anthropic import AsyncAnthropic

    client = AsyncAnthropic()
    prompt = _NARRATIVE_PROMPT.format(
        am_email=state["am_email"],
        actions_json=json.dumps(state["actions"], indent=2, default=str),
    )
    msg = await client.messages.create(
        model=MODEL,
        max_tokens=1500,
        messages=[{"role": "user", "content": prompt}],
    )
    return {"narrative": msg.content[0].text.strip()}


@traced(name="render_markdown")
async def _node_render(state: _BriefingState) -> dict[str, Any]:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    md = [f"# Daily briefing — {state['am_email']}", f"_{today}_", ""]
    if not state["actions"]:
        md.append("**Nothing to action today.** All your accounts look steady.")
    else:
        md.append(state["narrative"])
        md.append("")
        md.append("## Ranked actions")
        md.append("")
        for i, a in enumerate(state["actions"], 1):
            arrow = "🚨" if a["direction"] == "risk" else "🌱"
            md.append(
                f"{i}. {arrow} **{a['account']['name']}** ({a['account']['tier']}, "
                f"${int(a['account']['arr']):,} ARR) — `{a['signal_kind']}` "
                f"score {a['signal_score']:.2f}, weighted {a['weighted_score']:.2f}"
            )
            md.append(f"   - Why: {_one_line_reason(a)}")
        md.append("")
        md.append(f"_Generated by AAM. Reply with `/done`, `/snooze`, or `/wrong <id>` per item._")
    return {"markdown": "\n".join(md)}


async def _node_persist(state: _BriefingState) -> dict[str, Any]:
    bid = uuid.uuid4().hex[:10]
    async with session() as s:
        s.add(
            Briefing(
                id=bid,
                am_email=state["am_email"],
                generated_at=datetime.now(timezone.utc).replace(tzinfo=None),
                markdown=state["markdown"],
                actions=state["actions"],
            )
        )
    return {"events": [{"kind": "persisted", "briefing_id": bid}]}


@traced(name="teams_dm")
async def _node_teams_dm(state: _BriefingState) -> dict[str, Any]:
    """Best-effort Microsoft Teams personal DM via Bot Framework. No-op when
    bot credentials or AM conversation reference is missing; fail-soft on error."""
    try:
        result = await send_teams_dm(
            am_email=state["am_email"],
            narrative=state.get("narrative") or "",
            actions=state["actions"],
        )
        if result.get("skipped"):
            return {"events": [{"kind": "teams_dm_skipped", "reason": result.get("reason")}]}
        if result.get("ok"):
            return {"events": [{"kind": "teams_dm_delivered"}]}
        return {"events": [{"kind": "teams_dm_failed", "error": result.get("error")}]}
    except Exception as e:
        log.warning("aam.teams_dm.delivery_failed", err=str(e)[:300])
        return {"events": [{"kind": "teams_dm_failed", "error": str(e)[:300]}]}


@traced(name="teams_channel")
async def _node_teams_channel(state: _BriefingState) -> dict[str, Any]:
    """Best-effort Microsoft Teams channel delivery via Power Automate webhook.
    No-op when AAM_TEAMS_WEBHOOK_URL is unset; fail-soft on delivery error."""
    try:
        result = await post_teams_briefing(
            am_email=state["am_email"],
            narrative=state.get("narrative") or "",
            actions=state["actions"],
        )
        if result.get("skipped"):
            return {"events": [{"kind": "teams_skipped", "reason": result.get("reason")}]}
        if result.get("ok"):
            return {"events": [{"kind": "teams_delivered", "status": result.get("status")}]}
        return {"events": [{"kind": "teams_failed", "error": result.get("error")}]}
    except Exception as e:
        log.warning("aam.teams.delivery_failed", err=str(e)[:300])
        return {"events": [{"kind": "teams_failed", "error": str(e)[:300]}]}


@traced(name="slack_dm")
async def _node_slack_dm(state: _BriefingState) -> dict[str, Any]:
    """Best-effort Slack delivery. No-op when AAM_SLACK_BOT_TOKEN is unset.
    Failures are logged + recorded but do NOT fail the run — losing a
    delivery shouldn't lose the briefing."""
    try:
        result = await send_briefing_dm(
            am_email=state["am_email"],
            markdown=state["markdown"],
            actions=state["actions"],
        )
        if result.get("skipped"):
            return {"events": [{"kind": "slack_skipped", "reason": result.get("reason")}]}
        return {"events": [{"kind": "slack_delivered", "ts": result.get("ts"), "channel": result.get("channel")}]}
    except Exception as e:
        log.warning("aam.slack.delivery_failed", err=str(e)[:300])
        return {"events": [{"kind": "slack_failed", "error": str(e)[:300]}]}


# ---------- Graph ----------

def build_briefing_graph():
    g: StateGraph = StateGraph(_BriefingState)
    g.add_node("rank", _node_rank)
    g.add_node("narrative", _node_narrative)
    g.add_node("render", _node_render)
    g.add_node("persist", _node_persist)
    g.add_node("slack_dm", _node_slack_dm)
    g.add_node("teams_channel", _node_teams_channel)
    g.add_node("teams_dm", _node_teams_dm)
    g.add_edge(START, "rank")
    g.add_edge("rank", "narrative")
    g.add_edge("narrative", "render")
    g.add_edge("render", "persist")
    # Delivery channels run in parallel after persist, all fan into END.
    # Each is fail-soft, so an outage in one channel doesn't block the others.
    g.add_edge("persist", "slack_dm")
    g.add_edge("persist", "teams_channel")
    g.add_edge("persist", "teams_dm")
    g.add_edge("slack_dm", END)
    g.add_edge("teams_channel", END)
    g.add_edge("teams_dm", END)
    return g


async def generate_briefing(am_email: str) -> _BriefingState:
    graph = build_briefing_graph().compile()
    initial: _BriefingState = {"am_email": am_email, "events": []}
    return await graph.ainvoke(initial)


# ---------- Helpers ----------

def _one_line_reason(action: dict) -> str:
    d = action["detail"]
    kind = action["signal_kind"]
    if kind == "engagement_decay":
        return (
            f"Email opens dropped from {d['emails_opened_series'][0]} → "
            f"{d['emails_opened_series'][-1]} over the last 60 days; "
            f"last activity {d['last_activity_days_ago']} days ago."
        )
    if kind == "ticket_velocity_risk":
        return (
            f"{d['p1_count_30d']} P1s in 30 days, avg resolution "
            f"{d['avg_resolution_hours']:.1f}h, CSAT {d['csat']:.1f}."
        )
    if kind == "usage_growth":
        return (
            f"Logins trending +{int(d['trend_pct']*100)}%; "
            f"{d['modules_added']} new modules activated."
        )
    if kind == "module_gap":
        return f"Bought but never activated: {', '.join(d['unused_modules'])}."
    if kind == "renewal_proximity":
        return (
            f"Contract ends in {d['days_to_renewal']} days — "
            f"${int(d['arr_at_risk']):,} ARR at risk."
        )
    if kind == "doc_activity_decay":
        return f"SharePoint views down {int(d['trend_pct']*100)}%."
    if kind == "cosell_fit":
        return (
            f"Same industry ({d['industry']}) as healthy peer accounts "
            f"({len(d['peer_account_ids'])} of them) — warm intro / case study fit."
        )
    return json.dumps(d)


def _stub_narrative(actions: list[dict]) -> str:
    risks = [a for a in actions if a["direction"] == "risk"]
    opps = [a for a in actions if a["direction"] == "opportunity"]
    parts = []
    if risks:
        parts.append(
            f"You have **{len(risks)} accounts at risk today.** "
            f"Top concern: **{risks[0]['account']['name']}** "
            f"({risks[0]['signal_kind'].replace('_', ' ')})."
        )
    if opps:
        parts.append(
            f"You have **{len(opps)} expansion or co-sell openings.** "
            f"Strongest signal: **{opps[0]['account']['name']}** — "
            f"{opps[0]['signal_kind'].replace('_', ' ')}."
        )
    return " ".join(parts) or "Quiet day."


_NARRATIVE_PROMPT = """You write daily briefings for B2B cybersecurity account managers.

AM: {am_email}

Top ranked actions for today (JSON):
{actions_json}

Write a 2-4 sentence narrative summary that highlights the single most urgent
risk and the single most promising opportunity. Be specific (use account names
and numbers from the data). Tone: peer briefing a peer — direct, no fluff, no
emoji. Do NOT enumerate every action; just frame the day. Output plain text.
"""
